select top 10 
BackerId, ProjectId,
case when ProjectState = 'successful' then 1.0 else 0.0 end as state_successful,
case when ProjectState = 'failed' then 1.0 else 0.0 end as state_failed,
case when ProjectState = 'canceled' then 1.0 else 0.0 end as state_canceled,
case when ProjectState = 'suspended' then 1.0 else 0.0 end as state_suspended,
case when category = 'Pop' then 1.0 else 0.0 end as category_pop,
case when category = 'Open Hardware' then 1.0 else 0.0 end as category_open_hardware,
case when category = 'Board & Card Games' then 1.0 else 0.0 end as category_board_card_games,
case when category = 'World Music' then 1.0 else 0.0 end as category_world_music,
case when category = 'Fashion' then 1.0 else 0.0 end as category_fashion,
case when category = 'Nonfiction' then 1.0 else 0.0 end as category_nonfiction,
case when category = 'Dance' then 1.0 else 0.0 end as category_dance,
case when category = 'Webseries' then 1.0 else 0.0 end as category_webseries,
case when category = 'Film & Video' then 1.0 else 0.0 end as category_film_video,
case when category = 'Indie Rock' then 1.0 else 0.0 end as category_indie_rock,
case when category = 'Video Games' then 1.0 else 0.0 end as category_video_games,
case when category = 'Fiction' then 1.0 else 0.0 end as category_fiction,
case when category = 'Sculpture' then 1.0 else 0.0 end as category_sculpture,
case when category = 'Photography' then 1.0 else 0.0 end as category_photography,
case when category = 'Public Art' then 1.0 else 0.0 end as category_public_art,
case when category = 'Periodical' then 1.0 else 0.0 end as category_periodical,
case when category = 'Poetry' then 1.0 else 0.0 end as category_poetry,
case when category = 'Crafts' then 1.0 else 0.0 end as category_crafts,
case when category = 'Journalism' then 1.0 else 0.0 end as category_journalism,
case when category = 'Classical Music' then 1.0 else 0.0 end as category_classical_music,
case when category = 'Jazz' then 1.0 else 0.0 end as category_jazz,
case when category = 'Food' then 1.0 else 0.0 end as category_food,
case when category = 'Graphic Design' then 1.0 else 0.0 end as category_graphic_design,
case when category = 'Rock' then 1.0 else 0.0 end as category_rock,
case when category = 'Country & Folk' then 1.0 else 0.0 end as category_country_folk,
case when category = 'Art' then 1.0 else 0.0 end as category_art,
case when category = 'Theater' then 1.0 else 0.0 end as category_theater,
case when category = 'Electronic Music' then 1.0 else 0.0 end as category_electronic_music,
case when category = 'Open Software' then 1.0 else 0.0 end as category_open_software,
case when category = 'Narrative Film' then 1.0 else 0.0 end as category_narrative_film,
case when category = 'Painting' then 1.0 else 0.0 end as category_painting,
case when category = 'Animation' then 1.0 else 0.0 end as category_animation,
case when category = 'Comics' then 1.0 else 0.0 end as category_comics,
case when category = 'Publishing' then 1.0 else 0.0 end as category_publishing,
case when category = 'Art Book' then 1.0 else 0.0 end as category_art_book,
case when category = 'Short Film' then 1.0 else 0.0 end as category_short_film,
case when category = 'Mixed Media' then 1.0 else 0.0 end as category_mixed_media,
case when category = 'Hip-Hop' then 1.0 else 0.0 end as category_hip_hop,
case when category = 'Games' then 1.0 else 0.0 end as category_games,
case when category = 'Performance Art' then 1.0 else 0.0 end as category_performance_art,
case when category = 'Conceptual Art' then 1.0 else 0.0 end as category_conceptual_art,
case when category = 'Illustration' then 1.0 else 0.0 end as category_illustration,
case when category = 'Digital Art' then 1.0 else 0.0 end as category_digital_art,
case when category = 'Design' then 1.0 else 0.0 end as category_design,
case when category = 'Music' then 1.0 else 0.0 end as category_music,
case when category = 'Product Design' then 1.0 else 0.0 end as category_product_design,
case when category = 'Children''s Book' then 1.0 else 0.0 end as category_childrens_book,
case when category = 'Documentary' then 1.0 else 0.0 end as category_documentary,
case when category = 'Technology' then 1.0 else 0.0 end as category_technology,
case when goal <= 1000 then 1.0 else 0.0 end as goal_1_1000,
case when goal > 1000 and goal <= 5000 then 1.0 else 0.0 end as goal_1001_5000,
case when goal > 5000 and goal <= 10000 then 1.0 else 0.0 end as goal_5001_10000,
case when goal > 10000 and goal <= 30000 then 1.0 else 0.0 end as goal_10001_30000,
case when goal > 30000 and goal <= 100000 then 1.0 else 0.0 end as goal_30001_100000,
case when goal > 100000 and goal <= 250000 then 1.0 else 0.0 end as goal_100001_250000,
case when goal > 250000 then 1.0 else 0.0 end as goal_250001_plus
from [kick].[dbo].[project] p, [kick].[dbo].[projectbacker] pb
where p.Id = pb.ProjectId
and ProjectState is not null
and ProjectState not in ('live', 'purged')