SELECT top 10 
BackerId, count(*) as project_count,
avg(state_successful) as state_successful_avg, stdev(state_successful) as state_successful_stdev,
avg(state_failed) as state_failed_avg, stdev(state_failed) as state_failed_stdev,
avg(state_canceled) as state_canceled_avg, stdev(state_canceled) as state_canceled_stdev,
avg(state_suspended) as state_suspended_avg, stdev(state_suspended) as state_suspended_stdev,
avg(category_pop) as category_pop_avg, stdev(category_pop) as category_pop_stdev,
avg(category_open_hardware) as category_open_hardware_avg, stdev(category_open_hardware) as category_open_hardware_stdev,
avg(category_board_card_games) as category_board_card_games_avg, stdev(category_board_card_games) as category_board_card_games_stdev,
avg(category_world_music) as category_world_music_avg, stdev(category_world_music) as category_world_music_stdev,
avg(category_fashion) as category_fashion_avg, stdev(category_fashion) as category_fashion_stdev,
avg(category_nonfiction) as category_nonfiction_avg, stdev(category_nonfiction) as category_nonfiction_stdev,
avg(category_dance) as category_dance_avg, stdev(category_dance) as category_dance_stdev,
avg(category_webseries) as category_webseries_avg, stdev(category_webseries) as category_webseries_stdev,
avg(category_film_video) as category_film_video_avg, stdev(category_film_video) as category_film_video_stdev,
avg(category_indie_rock) as category_indie_rock_avg, stdev(category_indie_rock) as category_indie_rock_stdev,
avg(category_video_games) as category_video_games_avg, stdev(category_video_games) as category_video_games_stdev,
avg(category_fiction) as category_fiction_avg, stdev(category_fiction) as category_fiction_stdev,
avg(category_sculpture) as category_sculpture_avg, stdev(category_sculpture) as category_sculpture_stdev,
avg(category_photography) as category_photography_avg, stdev(category_photography) as category_photography_stdev,
avg(category_public_art) as category_public_art_avg, stdev(category_public_art) as category_public_art_stdev,
avg(category_periodical) as category_periodical_avg, stdev(category_periodical) as category_periodical_stdev,
avg(category_poetry) as category_poetry_avg, stdev(category_poetry) as category_poetry_stdev,
avg(category_crafts) as category_crafts_avg, stdev(category_crafts) as category_crafts_stdev,
avg(category_journalism) as category_journalism_avg, stdev(category_journalism) as category_journalism_stdev,
avg(category_classical_music) as category_classical_music_avg, stdev(category_classical_music) as category_classical_music_stdev,
avg(category_jazz) as category_jazz_avg, stdev(category_jazz) as category_jazz_stdev,
avg(category_food) as category_food_avg, stdev(category_food) as category_food_stdev,
avg(category_graphic_design) as category_graphic_design_avg, stdev(category_graphic_design) as category_graphic_design_stdev,
avg(category_rock) as category_rock_avg, stdev(category_rock) as category_rock_stdev,
avg(category_country_folk) as category_country_folk_avg, stdev(category_country_folk) as category_country_folk_stdev,
avg(category_art) as category_art_avg, stdev(category_art) as category_art_stdev,
avg(category_theater) as category_theater_avg, stdev(category_theater) as category_theater_stdev,
avg(category_electronic_music) as category_electronic_music_avg, stdev(category_electronic_music) as category_electronic_music_stdev,
avg(category_open_software) as category_open_software_avg, stdev(category_open_software) as category_open_software_stdev,
avg(category_narrative_film) as category_narrative_film_avg, stdev(category_narrative_film) as category_narrative_film_stdev,
avg(category_painting) as category_painting_avg, stdev(category_painting) as category_painting_stdev,
avg(category_animation) as category_animation_avg, stdev(category_animation) as category_animation_stdev,
avg(category_comics) as category_comics_avg, stdev(category_comics) as category_comics_stdev,
avg(category_publishing) as category_publishing_avg, stdev(category_publishing) as category_publishing_stdev,
avg(category_art_book) as category_art_book_avg, stdev(category_art_book) as category_art_book_stdev,
avg(category_short_film) as category_short_film_avg, stdev(category_short_film) as category_short_film_stdev,
avg(category_mixed_media) as category_mixed_media_avg, stdev(category_mixed_media) as category_mixed_media_stdev,
avg(category_hip_hop) as category_hip_hop_avg, stdev(category_hip_hop) as category_hip_hop_stdev,
avg(category_games) as category_games_avg, stdev(category_games) as category_games_stdev,
avg(category_performance_art) as category_performance_art_avg, stdev(category_performance_art) as category_performance_art_stdev,
avg(category_conceptual_art) as category_conceptual_art_avg, stdev(category_conceptual_art) as category_conceptual_art_stdev,
avg(category_illustration) as category_illustration_avg, stdev(category_illustration) as category_illustration_stdev,
avg(category_digital_art) as category_digital_art_avg, stdev(category_digital_art) as category_digital_art_stdev,
avg(category_design) as category_design_avg, stdev(category_design) as category_design_stdev,
avg(category_music) as category_music_avg, stdev(category_music) as category_music_stdev,
avg(category_product_design) as category_product_design_avg, stdev(category_product_design) as category_product_design_stdev,
avg(category_childrens_book) as category_childrens_book_avg, stdev(category_childrens_book) as category_childrens_book_stdev,
avg(category_documentary) as category_documentary_avg, stdev(category_documentary) as category_documentary_stdev,
avg(category_technology) as category_technology_avg, stdev(category_technology) as category_technology_stdev,
avg(goal_1_1000) as goal_1_1000_avg, stdev(goal_1_1000) as goal_1_1000_stdev,
avg(goal_1001_5000) as goal_1001_5000_avg, stdev(goal_1001_5000) as goal_1001_5000_stdev,
avg(goal_5001_10000) as goal_5001_10000_avg, stdev(goal_5001_10000) as goal_5001_10000_stdev,
avg(goal_10001_30000) as goal_10001_30000_avg, stdev(goal_10001_30000) as goal_10001_30000_stdev,
avg(goal_30001_100000) as goal_30001_100000_avg, stdev(goal_30001_100000) as goal_30001_100000_stdev,
avg(goal_100001_250000) as goal_100001_250000_avg, stdev(goal_100001_250000) as goal_100001_250000_stdev,
avg(goal_250001_plus) as goal_250001_plus_avg, stdev(goal_250001_plus) as goal_250001_plus_stdev
FROM backer_project
group by BackerId
having count(*) > 10

