#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[System.Data.Linq.Mapping.DatabaseAttribute(Name="AdventureWorksLT_Data")]
public partial class AWLinqDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertProduct(Product instance);
  partial void UpdateProduct(Product instance);
  partial void DeleteProduct(Product instance);
  #endregion
	
	public AWLinqDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["AdventureWorksLT_DataConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public AWLinqDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public AWLinqDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public AWLinqDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public AWLinqDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Product> Products
	{
		get
		{
			return this.GetTable<Product>();
		}
	}
}

[Table(Name="SalesLT.Product")]
public partial class Product : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ProductID;
	
	private string _Name;
	
	private string _ProductNumber;
	
	private string _Color;
	
	private decimal _StandardCost;
	
	private decimal _ListPrice;
	
	private string _Size;
	
	private System.Nullable<decimal> _Weight;
	
	private System.Nullable<int> _ProductCategoryID;
	
	private System.Nullable<int> _ProductModelID;
	
	private System.DateTime _SellStartDate;
	
	private System.Nullable<System.DateTime> _SellEndDate;
	
	private System.Nullable<System.DateTime> _DiscontinuedDate;
	
	private System.Data.Linq.Binary _ThumbNailPhoto;
	
	private string _ThumbnailPhotoFileName;
	
	private System.Guid _rowguid;
	
	private System.DateTime _ModifiedDate;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnProductIDChanging(int value);
    partial void OnProductIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnProductNumberChanging(string value);
    partial void OnProductNumberChanged();
    partial void OnColorChanging(string value);
    partial void OnColorChanged();
    partial void OnStandardCostChanging(decimal value);
    partial void OnStandardCostChanged();
    partial void OnListPriceChanging(decimal value);
    partial void OnListPriceChanged();
    partial void OnSizeChanging(string value);
    partial void OnSizeChanged();
    partial void OnWeightChanging(System.Nullable<decimal> value);
    partial void OnWeightChanged();
    partial void OnProductCategoryIDChanging(System.Nullable<int> value);
    partial void OnProductCategoryIDChanged();
    partial void OnProductModelIDChanging(System.Nullable<int> value);
    partial void OnProductModelIDChanged();
    partial void OnSellStartDateChanging(System.DateTime value);
    partial void OnSellStartDateChanged();
    partial void OnSellEndDateChanging(System.Nullable<System.DateTime> value);
    partial void OnSellEndDateChanged();
    partial void OnDiscontinuedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnDiscontinuedDateChanged();
    partial void OnThumbNailPhotoChanging(System.Data.Linq.Binary value);
    partial void OnThumbNailPhotoChanged();
    partial void OnThumbnailPhotoFileNameChanging(string value);
    partial void OnThumbnailPhotoFileNameChanged();
    partial void OnrowguidChanging(System.Guid value);
    partial void OnrowguidChanged();
    partial void OnModifiedDateChanging(System.DateTime value);
    partial void OnModifiedDateChanged();
    #endregion
	
	public Product()
	{
		OnCreated();
	}
	
	[Column(Storage="_ProductID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ProductID
	{
		get
		{
			return this._ProductID;
		}
		set
		{
			if ((this._ProductID != value))
			{
				this.OnProductIDChanging(value);
				this.SendPropertyChanging();
				this._ProductID = value;
				this.SendPropertyChanged("ProductID");
				this.OnProductIDChanged();
			}
		}
	}
	
	[Column(Storage="_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string Name
	{
		get
		{
			return this._Name;
		}
		set
		{
			if ((this._Name != value))
			{
				this.OnNameChanging(value);
				this.SendPropertyChanging();
				this._Name = value;
				this.SendPropertyChanged("Name");
				this.OnNameChanged();
			}
		}
	}
	
	[Column(Storage="_ProductNumber", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
	public string ProductNumber
	{
		get
		{
			return this._ProductNumber;
		}
		set
		{
			if ((this._ProductNumber != value))
			{
				this.OnProductNumberChanging(value);
				this.SendPropertyChanging();
				this._ProductNumber = value;
				this.SendPropertyChanged("ProductNumber");
				this.OnProductNumberChanged();
			}
		}
	}
	
	[Column(Storage="_Color", DbType="NVarChar(15)")]
	public string Color
	{
		get
		{
			return this._Color;
		}
		set
		{
			if ((this._Color != value))
			{
				this.OnColorChanging(value);
				this.SendPropertyChanging();
				this._Color = value;
				this.SendPropertyChanged("Color");
				this.OnColorChanged();
			}
		}
	}
	
	[Column(Storage="_StandardCost", DbType="Money NOT NULL")]
	public decimal StandardCost
	{
		get
		{
			return this._StandardCost;
		}
		set
		{
			if ((this._StandardCost != value))
			{
				this.OnStandardCostChanging(value);
				this.SendPropertyChanging();
				this._StandardCost = value;
				this.SendPropertyChanged("StandardCost");
				this.OnStandardCostChanged();
			}
		}
	}
	
	[Column(Storage="_ListPrice", DbType="Money NOT NULL")]
	public decimal ListPrice
	{
		get
		{
			return this._ListPrice;
		}
		set
		{
			if ((this._ListPrice != value))
			{
				this.OnListPriceChanging(value);
				this.SendPropertyChanging();
				this._ListPrice = value;
				this.SendPropertyChanged("ListPrice");
				this.OnListPriceChanged();
			}
		}
	}
	
	[Column(Storage="_Size", DbType="NVarChar(5)")]
	public string Size
	{
		get
		{
			return this._Size;
		}
		set
		{
			if ((this._Size != value))
			{
				this.OnSizeChanging(value);
				this.SendPropertyChanging();
				this._Size = value;
				this.SendPropertyChanged("Size");
				this.OnSizeChanged();
			}
		}
	}
	
	[Column(Storage="_Weight", DbType="Decimal(8,2)")]
	public System.Nullable<decimal> Weight
	{
		get
		{
			return this._Weight;
		}
		set
		{
			if ((this._Weight != value))
			{
				this.OnWeightChanging(value);
				this.SendPropertyChanging();
				this._Weight = value;
				this.SendPropertyChanged("Weight");
				this.OnWeightChanged();
			}
		}
	}
	
	[Column(Storage="_ProductCategoryID", DbType="Int")]
	public System.Nullable<int> ProductCategoryID
	{
		get
		{
			return this._ProductCategoryID;
		}
		set
		{
			if ((this._ProductCategoryID != value))
			{
				this.OnProductCategoryIDChanging(value);
				this.SendPropertyChanging();
				this._ProductCategoryID = value;
				this.SendPropertyChanged("ProductCategoryID");
				this.OnProductCategoryIDChanged();
			}
		}
	}
	
	[Column(Storage="_ProductModelID", DbType="Int")]
	public System.Nullable<int> ProductModelID
	{
		get
		{
			return this._ProductModelID;
		}
		set
		{
			if ((this._ProductModelID != value))
			{
				this.OnProductModelIDChanging(value);
				this.SendPropertyChanging();
				this._ProductModelID = value;
				this.SendPropertyChanged("ProductModelID");
				this.OnProductModelIDChanged();
			}
		}
	}
	
	[Column(Storage="_SellStartDate", DbType="DateTime NOT NULL")]
	public System.DateTime SellStartDate
	{
		get
		{
			return this._SellStartDate;
		}
		set
		{
			if ((this._SellStartDate != value))
			{
				this.OnSellStartDateChanging(value);
				this.SendPropertyChanging();
				this._SellStartDate = value;
				this.SendPropertyChanged("SellStartDate");
				this.OnSellStartDateChanged();
			}
		}
	}
	
	[Column(Storage="_SellEndDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> SellEndDate
	{
		get
		{
			return this._SellEndDate;
		}
		set
		{
			if ((this._SellEndDate != value))
			{
				this.OnSellEndDateChanging(value);
				this.SendPropertyChanging();
				this._SellEndDate = value;
				this.SendPropertyChanged("SellEndDate");
				this.OnSellEndDateChanged();
			}
		}
	}
	
	[Column(Storage="_DiscontinuedDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> DiscontinuedDate
	{
		get
		{
			return this._DiscontinuedDate;
		}
		set
		{
			if ((this._DiscontinuedDate != value))
			{
				this.OnDiscontinuedDateChanging(value);
				this.SendPropertyChanging();
				this._DiscontinuedDate = value;
				this.SendPropertyChanged("DiscontinuedDate");
				this.OnDiscontinuedDateChanged();
			}
		}
	}
	
	[Column(Storage="_ThumbNailPhoto", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
	public System.Data.Linq.Binary ThumbNailPhoto
	{
		get
		{
			return this._ThumbNailPhoto;
		}
		set
		{
			if ((this._ThumbNailPhoto != value))
			{
				this.OnThumbNailPhotoChanging(value);
				this.SendPropertyChanging();
				this._ThumbNailPhoto = value;
				this.SendPropertyChanged("ThumbNailPhoto");
				this.OnThumbNailPhotoChanged();
			}
		}
	}
	
	[Column(Storage="_ThumbnailPhotoFileName", DbType="NVarChar(50)")]
	public string ThumbnailPhotoFileName
	{
		get
		{
			return this._ThumbnailPhotoFileName;
		}
		set
		{
			if ((this._ThumbnailPhotoFileName != value))
			{
				this.OnThumbnailPhotoFileNameChanging(value);
				this.SendPropertyChanging();
				this._ThumbnailPhotoFileName = value;
				this.SendPropertyChanged("ThumbnailPhotoFileName");
				this.OnThumbnailPhotoFileNameChanged();
			}
		}
	}
	
	[Column(Storage="_rowguid", DbType="UniqueIdentifier NOT NULL")]
	public System.Guid rowguid
	{
		get
		{
			return this._rowguid;
		}
		set
		{
			if ((this._rowguid != value))
			{
				this.OnrowguidChanging(value);
				this.SendPropertyChanging();
				this._rowguid = value;
				this.SendPropertyChanged("rowguid");
				this.OnrowguidChanged();
			}
		}
	}
	
	[Column(Storage="_ModifiedDate", DbType="DateTime NOT NULL")]
	public System.DateTime ModifiedDate
	{
		get
		{
			return this._ModifiedDate;
		}
		set
		{
			if ((this._ModifiedDate != value))
			{
				this.OnModifiedDateChanging(value);
				this.SendPropertyChanging();
				this._ModifiedDate = value;
				this.SendPropertyChanged("ModifiedDate");
				this.OnModifiedDateChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
