<%@ Page Language="C#" MasterPageFile="~/MasterPage.master" Title="Untitled Page" %>

<script runat="server">
    protected void Page_InitComplete(object sender, EventArgs e) {
        DetailsView1.InitializeMaster(/*loadForeignKeys*/true);
    }
    protected void Page_Load(object sender, EventArgs e) {
        Title = "My Title for " + DetailsDataSource.TableName;
    }
</script>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <h2>Details about table <%= DetailsDataSource.TableName %></h2>

    <asp:ScriptManagerProxy runat="server" ID="ScriptManagerProxy1" />

    <asp:ValidationSummary ID="ValidationSummary1" runat="server" EnableClientScript="true"
        HeaderText="List of validation errors" />
    <asp:DynamicValidator runat="server" ID="DetailsViewValidator" ControlToValidate="DetailsView1" Display="None" />

    <br /><br />

    <asp:DynamicDetailsView ID="DetailsView1" runat="server" DataSourceID="DetailsDataSource"
        AutoGenerateEditButton="true" AutoGenerateDeleteButton="true" AutoGenerateInsertButton="true"
        CssClass="detailsview">
    </asp:DynamicDetailsView>

    <asp:LinqDataSource ID="DetailsDataSource" runat="server">
        <WhereParameters>
            <asp:DynamicQueryStringParameter />
        </WhereParameters>
    </asp:LinqDataSource>
</asp:Content>
