<%@ Page Language="C#" MasterPageFile="~/MasterPage.master" Title="Untitled Page" %>

<script runat="server">
    protected void Page_InitComplete(object sender, EventArgs e) {
        GridView1.InitializeMaster(/*loadForeignKeys*/true);
        GridView1.RegisterDetails(DetailsView1, /*loadForeignKeys*/true);
    }
    protected void Page_Load(object sender, EventArgs e) {
        Title = "My Title for " + GridDataSource.TableName;

        DynamicMetaTable metaTable = GridDataSource.GetMetaTable();
        if ((metaTable == null) || (metaTable.IsReadonly)) {
            DetailsPanel.Visible = false;
        }
    }
    protected void OnGridViewDataBound(object sender, EventArgs e) {
        if (GridView1.Rows.Count == 0) {
            DetailsView1.ChangeMode(DetailsViewMode.Insert);
        }
    }
    protected void OnFilterSelectedIndexChanged(object sender, EventArgs e) {
        GridView1.MarkAsReadOnly();
        DetailsView1.MarkAsReadOnly();
    }
    protected void OnGridViewRowEditing(object sender, EventArgs e) {
        DetailsView1.MarkAsReadOnly();
    }
    protected void OnGridViewSelectedIndexChanging(object sender, EventArgs e) {
        GridView1.MarkAsReadOnly();
        DetailsView1.MarkAsReadOnly();
    }
    protected void OnDetailsViewModeChanging(object sender, DetailsViewModeEventArgs e) {
        if (e.NewMode != DetailsViewMode.ReadOnly) {
            GridView1.MarkAsReadOnly();
        }
    }
</script>

<%@ Register  src="~/App_Shared/DynamicDataFields/GridViewPager.ascx" tagname="GridViewPager" tagprefix="uc1" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <h2><%= GridDataSource.TableName%> table</h2>

    <asp:ScriptManagerProxy runat="server" ID="ScriptManagerProxy1" />

    <asp:ValidationSummary ID="ValidationSummary1" runat="server" EnableClientScript="true"
        HeaderText="List of validation errors" />
    <asp:DynamicValidator runat="server" ID="GridViewValidator" ControlToValidate="GridView1" Display="None" />
    <asp:DynamicValidator runat="server" ID="DetailsViewValidator" ControlToValidate="DetailsView1" Display="None" />

    <br /><br />

    <asp:DynamicFilterRepeater ID="FilterRepeater" runat="server">
        <ItemTemplate>
            <%# Eval("Name") %>
            <asp:DynamicFilter runat="server" ID="DynamicFilter" OnSelectedIndexChanged="OnFilterSelectedIndexChanged" />
        </ItemTemplate>
        <FooterTemplate><br /><br /></FooterTemplate>
    </asp:DynamicFilterRepeater>

    <asp:DynamicGridView ID="GridView1" runat="server" DataSourceID="GridDataSource"
        AutoGenerateSelectButton="True" AutoGenerateEditButton="True" AutoGenerateDeleteButton="true"
        AllowPaging="True" AllowSorting="True" EnableQueryStringSelection="True" OnDataBound="OnGridViewDataBound"
        OnRowEditing="OnGridViewRowEditing" OnSelectedIndexChanging="OnGridViewSelectedIndexChanging"
        CssClass="gridview" AlternatingRowStyle-CssClass="even">
        <PagerStyle CssClass="Footer"/>        
        <PagerTemplate>
            <uc1:GridViewPager runat="server" />
        </PagerTemplate>
        <EmptyDataTemplate>
            There are currently no items in this table.
        </EmptyDataTemplate>
    </asp:DynamicGridView>

    <asp:LinqDataSource ID="GridDataSource" runat="server">
        <WhereParameters>
            <asp:DynamicControlParameter ControlID="FilterRepeater" />
        </WhereParameters>
    </asp:LinqDataSource>

    <asp:Panel ID="DetailsPanel" runat="server">
      <br /><br />

      <asp:DynamicDetailsView ID="DetailsView1" runat="server" DataSourceID="DetailsDataSource"
          AutoGenerateEditButton="true" AutoGenerateDeleteButton="true" AutoGenerateInsertButton="true"
          OnModeChanging="OnDetailsViewModeChanging" CssClass="detailsview">
      </asp:DynamicDetailsView>
      
      <asp:LinqDataSource ID="DetailsDataSource" runat="server">
          <WhereParameters>
              <asp:DynamicControlParameter ControlID="GridView1" />
          </WhereParameters>
      </asp:LinqDataSource>
    </asp:Panel>
</asp:Content>
